### ISSUE TITLE
Create Front-End Design for Page Layout

### ISSUE THREAD

**Issue by lennox55555** [lennox55555/Savvy-CSV#11]
### Description
We need a front-end design for the page layout of Savvy CSV. If you need inspiration, please refer to the previous page layout found at [savvycsv.com/applicator](http://savvycsv.com/applicator.html). The new page should be built using Node.js and React.

### Requirements
- **Technology Stack**: Node.js and React.
- **Scalability**: Ensure the code is scalable to accommodate future enhancements.
- **Readability**: Write clean, readable, and maintainable code.
- **Responsiveness**: The design should be fully responsive and work seamlessly on desktops, tablets, and mobile devices.
- **Consistency**: Maintain a consistent color scheme and typography throughout the site.
- **Accessibility**: Follow WCAG guidelines to ensure the design is accessible.

### Deliverables
- Source code for the front-end design using Node.js and React.
- Documentation on how to run and integrate the design with the existing back-end.

### Contact
If you have any questions or need further clarification, please reach out to Lennox Anderson at andersonlennox381@outlook.com.

Thank you for your contribution!

**Comment by jonahansmulcrone** [comment]
Set up React-App with Vite in /frontend. Looking for new issue in regards to new design.

**Comment by lennox55555** [comment]
Thank you Jonah!
