### ISSUE TITLE
Create Dark Mode Feature

### ISSUE THREAD

**Issue by jonahansmulcrone** [lennox55555/Savvy-CSV#31]
### Description

Create an aesthetic dark-mode feature for frontend in addition to existing light-mode.

### Requirements

1. Build a theme provider component to maintain global theme state.
2. Create custom css variables (properties) and theme types for both dark-mode and light-mode.

**Comment by lennox55555** [comment]
Great work, i will close this for now. I wonder how it would look with the columns headers be left with the color gradient.
